# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'read_data_new.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1671, 1517)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(250, 30, 1251, 1301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 300, 1171, 891))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.FigureLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.FigureLayout.setContentsMargins(0, 0, 0, 0)
        self.FigureLayout.setObjectName("FigureLayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(220, 190, 661, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.ToolbarLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.ToolbarLayout.setContentsMargins(0, 0, 0, 0)
        self.ToolbarLayout.setObjectName("ToolbarLayout")
        self.listView = QtWidgets.QListView(self.tab)
        self.listView.setGeometry(QtCore.QRect(220, 10, 371, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setObjectName("listView")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(41, 11, 152, 222))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LoadFile = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadFile.sizePolicy().hasHeightForWidth())
        self.LoadFile.setSizePolicy(sizePolicy)
        self.LoadFile.setObjectName("LoadFile")
        self.verticalLayout_3.addWidget(self.LoadFile)
        self.SetRefButton = QtWidgets.QPushButton(self.layoutWidget)
        self.SetRefButton.setObjectName("SetRefButton")
        self.verticalLayout_3.addWidget(self.SetRefButton)
        self.AddSampButton = QtWidgets.QPushButton(self.layoutWidget)
        self.AddSampButton.setObjectName("AddSampButton")
        self.verticalLayout_3.addWidget(self.AddSampButton)
        self.ClearButton = QtWidgets.QPushButton(self.layoutWidget)
        self.ClearButton.setObjectName("ClearButton")
        self.verticalLayout_3.addWidget(self.ClearButton)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(60, 190, 641, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.Toolbar_tab2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.Toolbar_tab2.setContentsMargins(0, 0, 0, 0)
        self.Toolbar_tab2.setObjectName("Toolbar_tab2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(60, 250, 1141, 971))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.Figure_tab2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.Figure_tab2.setContentsMargins(0, 0, 0, 0)
        self.Figure_tab2.setObjectName("Figure_tab2")
        self.SaveButton2 = QtWidgets.QPushButton(self.tab_2)
        self.SaveButton2.setGeometry(QtCore.QRect(750, 180, 150, 50))
        self.SaveButton2.setObjectName("SaveButton2")
        self.SelectButton2 = QtWidgets.QPushButton(self.tab_2)
        self.SelectButton2.setGeometry(QtCore.QRect(20, 60, 150, 46))
        self.SelectButton2.setObjectName("SelectButton2")
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(190, 21, 181, 128))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.SmoothCombo = QtWidgets.QComboBox(self.widget)
        self.SmoothCombo.setObjectName("SmoothCombo")
        self.verticalLayout_2.addWidget(self.SmoothCombo)
        self.SmoothButton2 = QtWidgets.QPushButton(self.widget)
        self.SmoothButton2.setObjectName("SmoothButton2")
        self.verticalLayout_2.addWidget(self.SmoothButton2)
        self.ClearButton2 = QtWidgets.QPushButton(self.tab_2)
        self.ClearButton2.setGeometry(QtCore.QRect(430, 110, 150, 46))
        self.ClearButton2.setObjectName("ClearButton2")
        self.widget1 = QtWidgets.QWidget(self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(380, 20, 301, 72))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.lineEdit2 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit2.setObjectName("lineEdit2")
        self.verticalLayout_4.addWidget(self.lineEdit2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_7.addWidget(self.lineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.widget2 = QtWidgets.QWidget(self.tab_2)
        self.widget2.setGeometry(QtCore.QRect(700, 20, 451, 131))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listView2 = QtWidgets.QListView(self.widget2)
        self.listView2.setObjectName("listView2")
        self.horizontalLayout.addWidget(self.listView2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.AddRefButton2 = QtWidgets.QPushButton(self.widget2)
        self.AddRefButton2.setObjectName("AddRefButton2")
        self.verticalLayout_5.addWidget(self.AddRefButton2)
        self.AddSampButton2 = QtWidgets.QPushButton(self.widget2)
        self.AddSampButton2.setObjectName("AddSampButton2")
        self.verticalLayout_5.addWidget(self.AddSampButton2)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 30, 211, 70))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_6.addWidget(self.comboBox)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(40, 31, 191, 631))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listView_ref = QtWidgets.QListView(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_ref.sizePolicy().hasHeightForWidth())
        self.listView_ref.setSizePolicy(sizePolicy)
        self.listView_ref.setObjectName("listView_ref")
        self.verticalLayout.addWidget(self.listView_ref)
        self.RemoveRefButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.RemoveRefButton.setObjectName("RemoveRefButton")
        self.verticalLayout.addWidget(self.RemoveRefButton)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.listView_sample = QtWidgets.QListView(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_sample.sizePolicy().hasHeightForWidth())
        self.listView_sample.setSizePolicy(sizePolicy)
        self.listView_sample.setObjectName("listView_sample")
        self.verticalLayout.addWidget(self.listView_sample)
        self.RemoveSampButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.RemoveSampButton.setObjectName("RemoveSampButton")
        self.verticalLayout.addWidget(self.RemoveSampButton)
        self.ClearallButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.ClearallButton.setObjectName("ClearallButton")
        self.verticalLayout.addWidget(self.ClearallButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1671, 38))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LoadFile.setText(_translate("MainWindow", "Load File"))
        self.SetRefButton.setText(_translate("MainWindow", "Set reference"))
        self.AddSampButton.setText(_translate("MainWindow", "Add to sample"))
        self.ClearButton.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Load Data"))
        self.SaveButton2.setText(_translate("MainWindow", "Save to file"))
        self.SelectButton2.setText(_translate("MainWindow", "Select trace"))
        self.label_3.setText(_translate("MainWindow", "Smooth type"))
        self.SmoothButton2.setText(_translate("MainWindow", "Smooth"))
        self.ClearButton2.setText(_translate("MainWindow", "Clear"))
        self.label_4.setText(_translate("MainWindow", "Window length"))
        self.label_6.setText(_translate("MainWindow", "Filter order"))
        self.AddRefButton2.setText(_translate("MainWindow", "Add to Reference"))
        self.AddSampButton2.setText(_translate("MainWindow", "Add to Sample"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Data Processing"))
        self.label_5.setText(_translate("MainWindow", "Deconvolution method"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Deconvolution"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Simulation"))
        self.label.setText(_translate("MainWindow", "Reference file name"))
        self.RemoveRefButton.setText(_translate("MainWindow", "Remove selected"))
        self.label_2.setText(_translate("MainWindow", "Sample file name"))
        self.RemoveSampButton.setText(_translate("MainWindow", "Remove selected"))
        self.ClearallButton.setText(_translate("MainWindow", "Clear all"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

