# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TFWindow_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1049, 876)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.WinComboBox = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WinComboBox.sizePolicy().hasHeightForWidth())
        self.WinComboBox.setSizePolicy(sizePolicy)
        self.WinComboBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.WinComboBox.setObjectName("WinComboBox")
        self.verticalLayout.addWidget(self.WinComboBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.SetWindowButton = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetWindowButton.sizePolicy().hasHeightForWidth())
        self.SetWindowButton.setSizePolicy(sizePolicy)
        self.SetWindowButton.setMaximumSize(QtCore.QSize(107, 50))
        self.SetWindowButton.setObjectName("SetWindowButton")
        self.gridLayout.addWidget(self.SetWindowButton, 0, 1, 1, 1)
        self.ClearButton = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClearButton.sizePolicy().hasHeightForWidth())
        self.ClearButton.setSizePolicy(sizePolicy)
        self.ClearButton.setMaximumSize(QtCore.QSize(80, 50))
        self.ClearButton.setObjectName("ClearButton")
        self.gridLayout.addWidget(self.ClearButton, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.OKButton = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OKButton.sizePolicy().hasHeightForWidth())
        self.OKButton.setSizePolicy(sizePolicy)
        self.OKButton.setMaximumSize(QtCore.QSize(80, 50))
        self.OKButton.setObjectName("OKButton")
        self.gridLayout.addWidget(self.OKButton, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.FigureRef = PlotWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FigureRef.sizePolicy().hasHeightForWidth())
        self.FigureRef.setSizePolicy(sizePolicy)
        self.FigureRef.setMinimumSize(QtCore.QSize(0, 341))
        self.FigureRef.setObjectName("FigureRef")
        self.FigureRef_FFT = PlotWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FigureRef_FFT.sizePolicy().hasHeightForWidth())
        self.FigureRef_FFT.setSizePolicy(sizePolicy)
        self.FigureRef_FFT.setMinimumSize(QtCore.QSize(0, 341))
        self.FigureRef_FFT.setObjectName("FigureRef_FFT")
        self.verticalLayout_2.addWidget(self.splitter)
        self.FigureSample = PlotWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FigureSample.sizePolicy().hasHeightForWidth())
        self.FigureSample.setSizePolicy(sizePolicy)
        self.FigureSample.setMinimumSize(QtCore.QSize(0, 422))
        self.FigureSample.setObjectName("FigureSample")
        self.verticalLayout_2.addWidget(self.FigureSample)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Window Function"))
        self.SetWindowButton.setText(_translate("Dialog", "Set Time Window"))
        self.ClearButton.setText(_translate("Dialog", "Clear"))
        self.OKButton.setText(_translate("Dialog", "OK"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
